; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = espidf


; [env:esp32-s3-devkitc-1]
; platform = espressif32
; framework = espidf
; board = esp32-s3-devkitc-1

; 시리얼 모니터 속도
monitor_speed = 115200

; N16R8 스펙을 위한 플래시 및 PSRAM 빌드 플래그 설정
board_build.arduino.memory_type = qio_opi ; 플래시 QIO, PSRAM OPI 설정
board_build.flash_size = 16MB

build_flags =
    -D CORE_DEBUG_LEVEL=5
    ; 8MB OSPI PSRAM 활성화를 위한 IDF 옵션 (필요시 자동 매핑)
    -D BOARD_HAS_PSRAM